### PR TITLE
add dam break mesh and initial conditions

### PR DESCRIPTION
**Pull request by donghuix**
Add .exo mesh file (with flat topo, i.e., z = 0) and corresponding initiation condition with wet downstream
(PETSc binary format) for dam break example. In the initial condition, the depth of the left of the 
dam = 10[m] and the depth of the right of the dam = 5 [m].

### CODE REVIEW

**Review by jeff-cohere — APPROVED** [review]
Thanks!

**Comment by jedbrown** [comment]
Thanks @donghuix! Do you have the Cubit journal file that created this mesh, so we can use it to make different resolution and topology meshes in the future?

**Comment by xdongh** [comment]
> 



> 

Hi @jedbrown, I used Matlab to create the mesh and initial condition file. I can upload the scripts to Github if you think that will be useful.

**Comment by donghuix** [comment]
> Thanks @donghuix! Do you have the Cubit journal file that created this mesh, so we can use it to make different resolution and topology meshes in the future?

Hi @jedbrown, I used Matlab to create the mesh and initial condition files. I can upload the scripts to Github if you think that will be helpful.

**Comment by jedbrown** [comment]
Oh, I didn't realize there's a Matlab tool to write Exodus. In any case, I think there will be reason to want different resolutions. Honestly, I'd make this one coarser so it can be used for short-running testing and add the script so finer meshes can be generated. Also, it looks like boundaries have not been labeled.

Cf. this domain in Gmsh: https://github.com/RDycore/RDycore/issues/13#issuecomment-1402784871

**Comment by knepley** [comment]
@jedbrown We can also just use `DMRefine()` to get more refined meshes.

**Comment by jedbrown** [comment]
True, so long as the resolution stays uniform as it is here, and it would probably take some work to change that in the Matlab script.

**Comment by donghuix** [comment]
> Oh, I didn't realize there's a Matlab tool to write Exodus. In any case, I think there will be reason to want different resolutions. Honestly, I'd make this one coarser so it can be used for short-running testing and add the script so finer meshes can be generated. Also, it looks like boundaries have not been labeled.
> 
> Cf. this domain in Gmsh: [RDycore/RDycore#13 (comment)](https://github.com/RDycore/RDycore/issues/13#issuecomment-1402784871)

Hi @jedbrown. In previous project, I realized the Exodus file is netcdf format with specified dimensions and attributes. Then I decided to use Matlab to create Exodus mesh file because I need to read complex geometry (i.e., watershed boundary) in shapefile or derive the geometry based on topography. Something I didn't figure out is read boundaries from the Exodus file. Do you have an example Exodus file that have boundaries labelled? I can add it into my script. 

For the domain only contains the exterior boundary (e.g., this simple dam break example), we may not need the boundary labels because @bishtgautam's code determines the boundary edge when it is only connected to a cell. But I agree it will be very useful to have boundaries labelled as we will have more complex boundary conditions in a realistic application. 

I can generate a coarser mesh for the dam break example. This mesh has dx=dy=1 [m], which is same as previous study. A coarser resolution will be better for the test purpose, for example, dx=dy= 5 [m]?.

**Comment by jeff-cohere** [comment]
For the record, there's a [gmsh -> exodus converter](https://iapcs.github.io/gmsh-exodus-converter/) that we could try to use to generate an Exodus mesh from [the one that Jed is referring to](https://github.com/RDycore/RDycore/issues/13#issuecomment-1402784871). I think [meshio](https://github.com/nschloe/meshio) also allows this. Does this sound reasonable?

**Comment by knepley** [comment]
@donghuix PETSc can write Exodus files, so we can look at that code to determine how to write the boundaries.

**Comment by jedbrown** [comment]
What is the attraction of Exodus in the first place? It's kind of fragile to build (much longer chain of dependencies as compared to Gmsh (PETSc's reader has no dependencies) or CGNS (few seconds + hdf5). We can use Exodus meshes if they're available, but I don't think we need to go out of our way to center it in a workflow.

As an example of Exodus side sets, you can see `sevenside-quad.exo` [here](https://gitlab.com/petsc/petsc/-/tree/main/share/petsc/datafiles/meshes).

**Comment by donghuix** [comment]
> @donghuix PETSc can write Exodus files, so we can look at that code to determine how to write the boundaries.

Thank you, @knepley!

**Comment by bishtgautam** [comment]
>What is the attraction of Exodus in the first place? 

The reason we are using Exodus is none other than the fact we (@donghuix and I) know how to write a mesh in `.exo` format. I'm happy to write new meshes in any other format (Gmsh/hdf5/etc) as long as I can figure out how to write meshes in those formats.

**Comment by jedbrown** [comment]
Is the Gmsh example I made for this problem not suitable? We can produce quad meshes the same way (structured or non-uniform, say, with refinement near the corners). That was like a 10 minute job, included labeled faces, and will be easy to modify. (If you're going to be creating meshes in Matlab and you want to use your Exodus writer, that's fine. But we surely don't need to convert Gmsh to Exodus or otherwise unnecessarily go through Exodus.)

**Comment by donghuix** [comment]
Modify the dam break example mesh to be much coarser resolution, see the figure below:

Screen Shot 2023-02-08 at 10 10 55 AM

And a wet downstream initial condition:
 
Screen Shot 2023-02-08 at 10 25 32 AM


@jeff-cohere, @bishtgautam, let me know if you have any issues when running with it.

**Comment by jeff-cohere** [comment]
I am able to successfully run this example.

One last thing before we merge: can you write something in `swe_roe/README.md` about `ex2a` and `ex2b`, just so folks understand what these example programs are doing?

Also, can you include the Matlab code that you used to generate the mesh above?

**Comment by bishtgautam** [comment]
@donghuix in the last commit you deleted the files instead of renaming them.

**Review by jeff-cohere — APPROVED** [review]

**Pull request merged**
