### PR TITLE
add script and note for code verification

### PR DESCRIPTION
**Pull request by donghuix**

### CODE REVIEW

**Review by bishtgautam — COMMENTED** [review]
@donghuix Thanks for this PR. Is it okay if I make a commit in your branch to avoid having `write_exodus_file_v1.m` and `write_exodus_file_v2.m`?

**Comment by xdongh** [comment]
> @donghuix Thanks for this PR. Is it okay if I make a commit in your branch to avoid having `write_exodus_file_v1.m` and `write_exodus_file_v2.m`?

Sure, feel free to make any modifications.

**Comment by bishtgautam** [comment]
@donghuix Do you also have a script that computes and plots the error norms?

**Comment by donghuix** [comment]
> @donghuix Do you also have a script that computes and plots the error norms?

Yes, I have. Should I make a commit for it?

**Comment by bishtgautam** [comment]
Yes, please commit it here.

**Comment by donghuix** [comment]
> Yes, please commit it here.

I committed the Matlab script and some code modifications to add an option to only output the final solution. Feel free to edit it.

**Pull request merged**
